### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by ai-qui** [phlowers/.github#5]
### Describe the expected behavior

A code of conduct should be added

### Extra Information

cf. #2

**Comment by adriengoeller** [comment]
I propose to to inspiration form [numpy](https://numpy.org/code-of-conduct/)
Perhaps the sections "Reporting Guidelines" and "Incident reporting resolution & Code of Conduct enforcement" could be removed for now.

**Comment by annetill** [comment]
> I propose to to inspiration form [numpy](https://numpy.org/code-of-conduct/) Perhaps the sections "Reporting Guidelines" and "Incident reporting resolution & Code of Conduct enforcement" could be removed for now. What do you think @annetill ?

I think the most important sections are the "specific guidelines" and how to report an incident. You must keep such a section because we have to imagine after reporting an incident several follow-ups: first we can imagine just a reminder to the code of conduct, then a discussion, but secondly we have to apply a stronger policy. The reporting incident section can be written in a second time.

**Comment by adriengoeller** [comment]
@ai-qui proposes some changes in the "diversity statement" section: replace the list with the list given in §Our Standards in the [PSF code of conduct](https://policies.python.org/python.org/code-of-conduct/)
